//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Views.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceSite {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceSite() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web.Views.Shared.ResourceSite", typeof(ResourceSite).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Info.
        /// </summary>
        public static string Account_Info {
            get {
                return ResourceManager.GetString("Account_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Type.
        /// </summary>
        public static string Account_Type {
            get {
                return ResourceManager.GetString("Account_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add to cart.
        /// </summary>
        public static string add_to_cart {
            get {
                return ResourceManager.GetString("add_to_cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add to wishlist.
        /// </summary>
        public static string add_to_wishlist {
            get {
                return ResourceManager.GetString("add_to_wishlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your review.
        /// </summary>
        public static string Add_your_review {
            get {
                return ResourceManager.GetString("Add_your_review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Dashboard.
        /// </summary>
        public static string Admin_Dashboard {
            get {
                return ResourceManager.GetString("Admin_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Categories.
        /// </summary>
        public static string All_Categories {
            get {
                return ResourceManager.GetString("All_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ecommerce.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash.
        /// </summary>
        public static string Cash {
            get {
                return ResourceManager.GetString("Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deliverd Orders.
        /// </summary>
        public static string Deliverd_Orders {
            get {
                return ResourceManager.GetString("Deliverd_Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Address.
        /// </summary>
        public static string Enter_Address {
            get {
                return ResourceManager.GetString("Enter_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Email.
        /// </summary>
        public static string Enter_Your_Email {
            get {
                return ResourceManager.GetString("Enter_Your_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FREE.
        /// </summary>
        public static string FREE {
            get {
                return ResourceManager.GetString("FREE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string Full_Name {
            get {
                return ResourceManager.GetString("Full_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hot deal this week.
        /// </summary>
        public static string hot_deal_this_week {
            get {
                return ResourceManager.GetString("hot_deal_this_week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Stock.
        /// </summary>
        public static string In_Stock {
            get {
                return ResourceManager.GetString("In_Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketed.
        /// </summary>
        public static string Marketed {
            get {
                return ResourceManager.GetString("Marketed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW.
        /// </summary>
        public static string NEW {
            get {
                return ResourceManager.GetString("NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Products.
        /// </summary>
        public static string New_Products {
            get {
                return ResourceManager.GetString("New_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEWSLETTER.
        /// </summary>
        public static string NEWSLETTER {
            get {
                return ResourceManager.GetString("NEWSLETTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer price.
        /// </summary>
        public static string Offer_price {
            get {
                return ResourceManager.GetString("Offer_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Date.
        /// </summary>
        public static string Order_Date {
            get {
                return ResourceManager.GetString("Order_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order stutes.
        /// </summary>
        public static string order_Stutes {
            get {
                return ResourceManager.GetString("order_Stutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayPal.
        /// </summary>
        public static string PayPal {
            get {
                return ResourceManager.GetString("PayPal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place order.
        /// </summary>
        public static string Place_order {
            get {
                return ResourceManager.GetString("Place_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRODUCT.
        /// </summary>
        public static string PRODUCT {
            get {
                return ResourceManager.GetString("PRODUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Rate According to Customers.
        /// </summary>
        public static string Product_Rate_According_to_Customers {
            get {
                return ResourceManager.GetString("Product_Rate_According_to_Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit.
        /// </summary>
        public static string Profit {
            get {
                return ResourceManager.GetString("Profit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty Avaiable Now.
        /// </summary>
        public static string Qty_Avaiable_Now {
            get {
                return ResourceManager.GetString("Qty_Avaiable_Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register First.
        /// </summary>
        public static string Register_First {
            get {
                return ResourceManager.GetString("Register_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Products.
        /// </summary>
        public static string Related_Products {
            get {
                return ResourceManager.GetString("Related_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review(s).
        /// </summary>
        public static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search here.
        /// </summary>
        public static string Search_here {
            get {
                return ResourceManager.GetString("Search_here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell Count.
        /// </summary>
        public static string Sell_Count {
            get {
                return ResourceManager.GetString("Sell_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shiping.
        /// </summary>
        public static string Shiping {
            get {
                return ResourceManager.GetString("Shiping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop now.
        /// </summary>
        public static string Shop_now {
            get {
                return ResourceManager.GetString("Shop_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up for the.
        /// </summary>
        public static string Sign_Up_for_the {
            get {
                return ResourceManager.GetString("Sign_Up_for_the", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        public static string Store {
            get {
                return ResourceManager.GetString("Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe.
        /// </summary>
        public static string Subscribe {
            get {
                return ResourceManager.GetString("Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Balance.
        /// </summary>
        public static string The_Balance {
            get {
                return ResourceManager.GetString("The_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top selling.
        /// </summary>
        public static string Top_selling {
            get {
                return ResourceManager.GetString("Top_selling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL.
        /// </summary>
        public static string TOTAL {
            get {
                return ResourceManager.GetString("TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Personal Info.
        /// </summary>
        public static string Update_Personal_Info {
            get {
                return ResourceManager.GetString("Update_Personal_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor.
        /// </summary>
        public static string Vendor {
            get {
                return ResourceManager.GetString("Vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor Name.
        /// </summary>
        public static string Vendor_Name {
            get {
                return ResourceManager.GetString("Vendor_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa.
        /// </summary>
        public static string Visa {
            get {
                return ResourceManager.GetString("Visa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet.
        /// </summary>
        public static string Wallet {
            get {
                return ResourceManager.GetString("Wallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw.
        /// </summary>
        public static string Withdraw {
            get {
                return ResourceManager.GetString("Withdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withrawn Balance.
        /// </summary>
        public static string Withrawn_Balance {
            get {
                return ResourceManager.GetString("Withrawn_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should be authonticated to add to wishlist.
        /// </summary>
        public static string You_should_be_authonticated {
            get {
                return ResourceManager.GetString("You_should_be_authonticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Cart.
        /// </summary>
        public static string Your_Cart {
            get {
                return ResourceManager.GetString("Your_Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Cart is empty add more products now!.
        /// </summary>
        public static string Your_Cart_is_empty {
            get {
                return ResourceManager.GetString("Your_Cart_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Name.
        /// </summary>
        public static string Your_Name {
            get {
                return ResourceManager.GetString("Your_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Order.
        /// </summary>
        public static string Your_Order {
            get {
                return ResourceManager.GetString("Your_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Rating.
        /// </summary>
        public static string Your_Rating {
            get {
                return ResourceManager.GetString("Your_Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Review.
        /// </summary>
        public static string Your_Review {
            get {
                return ResourceManager.GetString("Your_Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Wishlist.
        /// </summary>
        public static string Your_Wishlist {
            get {
                return ResourceManager.GetString("Your_Wishlist", resourceCulture);
            }
        }
    }
}
